######################################################################
#       Global SERVICE exposed to outside via K8S Master Node        #
#  kubectl port-forward service/viso-configserver-service 7088:8888  #
######################################################################

apiVersion:       v1
kind:             Service

metadata:
  name:           viso-configserver-service

spec:
  selector:
    app:          viso-configserver-pod

  type:           NodePort

  ports:
    - port:       8888
      targetPort: 8888
